trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'

- script: |
    pip install -r requirements.txt
    pytest tests/
  displayName: 'Run Tests'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure-DevOps-Connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az storage blob upload-batch \
        --destination build-artifacts \
        --source ./dist \
        --account-name devopslearningstorage
  displayName: 'Upload Artifacts to Blob Storage'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'python-api-build'
